# Generated by Django 5.2.11 on 2026-02-23 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance_credits", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=16)),
                ("total_loaded_credits", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=16)),
                ("total_used_credits", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("load", "Load"),
                            ("image_consume", "Image Consume"),
                            ("text_consume", "Text Consume"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("credits_delta", models.DecimalField(decimal_places=4, max_digits=16)),
                ("unit_count", models.PositiveIntegerField(default=0)),
                ("feature", models.CharField(blank=True, default="", max_length=64)),
                ("reference_id", models.CharField(blank=True, default="", max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["user", "created_at"], name="usage_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["event_type", "created_at"], name="usage_type_created_idx"),
        ),
    ]
