# Generated by Django 5.2.11 on 2026-02-23 00:01

from django.conf import settings
from django.db import migrations


def _backfill_wallets(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    UsageWallet = apps.get_model("usage", "UsageWallet")
    for user in User.objects.all().iterator():
        UsageWallet.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_backfill_wallets, migrations.RunPython.noop),
    ]
