# Generated by Django 5.2.11 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0002_imagejob_result_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagejob",
            name="kind",
            field=models.CharField(
                choices=[("studio", "Studio"), ("feedback", "Feedback")],
                default="studio",
                max_length=16,
            ),
        ),
    ]
