# Generated by Django 5.2.11 on 2026-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_alter_providerkey_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("nano_banana", "Nano Banana"),
                            ("deepseek", "DeepSeek"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(max_length=128)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "model"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "model"),
                        name="gateway_provider_model_unique",
                    )
                ],
            },
        ),
    ]
