# Generated by Django 5.2.11 on 2026-07-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0003_providermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerkey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google"),
                    ("nano_banana", "Nano Banana"),
                    ("deepseek", "DeepSeek"),
                    ("glm", "GLM"),
                    ("kimi", "Kimi"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providermodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google"),
                    ("nano_banana", "Nano Banana"),
                    ("deepseek", "DeepSeek"),
                    ("glm", "GLM"),
                    ("kimi", "Kimi"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
    ]
